/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vfernand' at '12/23/16 7:22 PM' with Gradle 3.2.1
 *
 * @author vfernand, @date 12/23/16 7:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
